---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

providers:
  openweathermap: 758ae83bd14f27b7ffe0b70e2b332866
  weatherapi: 758ae83bd14f27b7ffe0b70e2b332866

layout:
    Bookmark Group on First Tab: 
      tab: Main

    Home Network: 
      tab: Main

    Monitoring: 
      tab: Main

    Media: 
      tab: Main

    Tools: 
      tab: Main

    Overig: 
      tab: Main

    Graphs: 
      tab: Status

    Glances:
      tab: Status
