---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: Paulus HomePage
useEqualHeights: true

background:
  image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg # image small memory by Mikael Gustafsson
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

providers:
  openweathermap: 758ae83bd14f27b7ffe0b70e2b332866
  weatherapi: 758ae83bd14f27b7ffe0b70e2b332866
  
layout:
    Bookmark Group on First Tab: 
      tab: Main

    Home Network: 
      tab: Main

    Monitoring: 
      tab: Main

    Media & Data 1: 
      tab: Main

    Media & Data 2: 
      tab: Main

    Overig: 
      tab: Main

    Dev: 
      tab: Main
      icon: https://raw.githubusercontent.com/101br03k/docker-setup/main/dashboard-icons/code-tech-dev-icon-512x512-white.png

    Upcoming:
      tab: Main

    Pihole:
      tab: Status

    Stats: 
      tab: Status

    Glances:
      tab: Status
