name: Update Homepage Config

on:
  push:
    branches:
      - main
      - test
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull Homepage Config
        uses: appleboy/scp-action@master
        with:
          username: adm-aw
          host: paulus-100-docker.hl
          key: ${{ secrets.SSH_paulus_100_docker }}
          source: '/*'
          target: /docker/docker-setup/homepage-config/
          strip_components: 3
          overwrite: true
