name: Update Docker Compose File

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download new Homepage config
        uses: fifsky/ssh-action@master
        with:
          user: adm-aw
          host: 192.168.0.21
          key: ${{ secrets.SSH_paulus_100_docker }}
          pass: ${{ secrets.pass_docker_100 }}
          command: |
            cd /docker/homepage-config/
            ls -alh
            ./download-config.sh
            ls -alh
