name: Download new HomePage config

on:
  push:
    branches:
      - migrate-to-pve

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download new HomePage config
        uses: fifsky/ssh-action@master
        with:
          user: adm-aw
          host: 192.168.0.11
          key: ${{ secrets.SSH_pve_100_docker }}
          pass: ${{ secrets.pass_docker_100 }}
          command: |
            cd /docker/homepage-config/
            ls -alh
            ./download-config.sh
            ls -alh
