name: Update Docker Compose File

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: your-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restart Docker Container
        uses: fifsky/ssh-action@master
        with:
          user: adm-aw
          host: paulus-101-docker.hl
          key: ${{ secrets.SSH_paulus_100_docker }}
          command: |
            cd /docker/docker-setup/
